name: PetJournalAndroid

# Eventos/Events: vão disparar quando uma das ações acontecerem.
# EXEMPLO: evento abaixo dispara quando acontecer um push em uma das branches explicitadas
on:
  push:
    branches:
      - develop
      - cicdtest
      - 'instTest/nameAndGender'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.0

      - name: Set up JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '1.8'
          distribution: 'adopt'

      - name: Gradle Build
        run: ./gradlew build
      
      - name: Gradle Test
        run: ./gradlew test
